# Generated by Django 3.1 on 2020-09-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='seminar',
            name='count',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='seminar',
            name='online',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='seminar',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
