# Generated by Django 3.1 on 2020-09-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_auto_20200926_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
