# Generated by Django 3.1 on 2020-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0003_auto_20200926_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseminar',
            name='dropped_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userseminar',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'participant'), (1, 'instructor')], db_index=True, default=None),
        ),
    ]
