# Generated by Django 3.1 on 2020-09-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0004_auto_20200926_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userseminar',
            old_name='dropped_out',
            new_name='dropped_at',
        ),
    ]
