# Generated by Django 3.1 on 2020-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0005_auto_20200926_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseminar',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'participant'), (1, 'instructor')], default=None),
        ),
    ]
