# Generated by Django 3.1 on 2020-09-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0007_auto_20200927_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='capacity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='count',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='online',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='time',
            field=models.TimeField(),
        ),
    ]
