# Generated by Django 3.1 on 2020-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0008_auto_20200927_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
