# Generated by Django 3.1 on 2020-10-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0010_auto_20201008_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
