# Generated by Django 3.1 on 2020-09-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200926_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='accepted',
            field=models.BooleanField(default=None),
        ),
    ]
